name: liga_roca
description: App de futbol Liga Roca con noticias y fixture.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Iconos
  cupertino_icons: ^1.0.2
  
  # Estado y Utilidades
  provider: ^6.0.0
  intl: ^0.18.0
  
  # Firebase
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
